# Generated by Django 5.0.7 on 2024-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_background',
        ),
    ]
