# Generated by Django 5.0.7 on 2024-07-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0009_user_confirmation_code_user_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
    ]
