# Generated by Django 5.0.7 on 2024-07-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0011_profile_profile_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
