# Generated by Django 5.0.7 on 2024-07-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0014_remove_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
