# Generated by Django 5.0.7 on 2024-07-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0016_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
