# Generated by Django 5.0.7 on 2024-07-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0017_post_comment_number_post_like_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='post_number',
            field=models.IntegerField(default=0),
        ),
    ]
