# Generated by Django 5.0.7 on 2024-07-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0018_user_like_number_user_post_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_number',
            field=models.IntegerField(default=0),
        ),
    ]
