# Generated by Django 5.0.7 on 2024-07-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0019_remove_user_like_number_remove_user_post_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
